/**
 * Chat Mock Data & Simulation
 * 백엔드 없이 채팅 기능을 테스트하기 위한 mock 데이터
 */

import type {
  ChatRoom,
  ChatMessage,
  ChatParticipant,
} from '../types';

// ============ Mock 참여자 데이터 ============

export const mockParticipants: Record<string, ChatParticipant> = {
  student1: {
    userId: 'student1',
    name: '김학생',
    role: 'student',
    profileImage: 'https://i.pravatar.cc/150?img=3',
    status: 'online',
    lastSeen: new Date().toISOString(),
  },
  expert1: {
    userId: 'expert1',
    name: '김논술',
    role: 'expert',
    profileImage: 'https://i.pravatar.cc/150?img=11',
    status: 'online',
    lastSeen: new Date().toISOString(),
  },
  expert2: {
    userId: 'expert2',
    name: '박전문',
    role: 'expert',
    profileImage: 'https://i.pravatar.cc/150?img=12',
    status: 'away',
    lastSeen: new Date(Date.now() - 1800000).toISOString(),
  },
  consultant1: {
    userId: 'consultant1',
    name: '최입시',
    role: 'consultant',
    profileImage: 'https://i.pravatar.cc/150?img=5',
    status: 'online',
    lastSeen: new Date().toISOString(),
  },
  consultant2: {
    userId: 'consultant2',
    name: '강컨설팅',
    role: 'consultant',
    profileImage: 'https://i.pravatar.cc/150?img=8',
    status: 'offline',
    lastSeen: new Date(Date.now() - 86400000).toISOString(),
  },
  support1: {
    userId: 'support1',
    name: '고객센터',
    role: 'admin',
    profileImage: undefined,
    status: 'online',
    lastSeen: new Date().toISOString(),
  },
};

// ============ Mock 채팅방 데이터 ============

export const mockChatRooms: ChatRoom[] = [
  {
    id: 'room1',
    type: 'essay_review',
    participants: [mockParticipants.student1, mockParticipants.expert1],
    lastMessage: {
      id: 'msg1-10',
      roomId: 'room1',
      senderId: 'expert1',
      senderName: '김논술',
      senderRole: 'expert',
      content: '논리 전개 부분을 수정해보시면 좋을 것 같습니다.',
      type: 'text',
      status: 'delivered',
      isPinned: false,
      isEdited: false,
      readBy: ['expert1'],
      createdAt: new Date(Date.now() - 300000).toISOString(),
    },
    unreadCount: 2,
    isPinned: true,
    isMuted: false,
    metadata: {
      essayId: '1',
      essayTitle: '서울대 2024학년도 모의논술',
    },
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 300000).toISOString(),
  },
  {
    id: 'room2',
    type: 'consulting',
    participants: [mockParticipants.student1, mockParticipants.consultant1],
    lastMessage: {
      id: 'msg2-5',
      roomId: 'room2',
      senderId: 'consultant1',
      senderName: '최입시',
      senderRole: 'consultant',
      content: '다음 상담 일정을 잡아볼까요?',
      type: 'text',
      status: 'read',
      isPinned: false,
      isEdited: false,
      readBy: ['student1', 'consultant1'],
      createdAt: new Date(Date.now() - 3600000).toISOString(),
    },
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
    metadata: {
      consultingSessionId: 'session1',
    },
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'room3',
    type: 'essay_review',
    participants: [mockParticipants.student1, mockParticipants.expert2],
    lastMessage: {
      id: 'msg3-3',
      roomId: 'room3',
      senderId: 'student1',
      senderName: '김학생',
      senderRole: 'student',
      content: '첨삭 결과 확인했습니다. 감사합니다!',
      type: 'text',
      status: 'delivered',
      isPinned: false,
      isEdited: false,
      readBy: ['student1'],
      createdAt: new Date(Date.now() - 86400000).toISOString(),
    },
    unreadCount: 0,
    isPinned: false,
    isMuted: false,
    metadata: {
      essayId: '2',
      essayTitle: '연세대 인문계열 논술',
    },
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'room4',
    type: 'support',
    participants: [mockParticipants.student1, mockParticipants.support1],
    lastMessage: {
      id: 'msg4-2',
      roomId: 'room4',
      senderId: 'support1',
      senderName: '고객센터',
      senderRole: 'admin',
      content: '문의하신 내용 확인했습니다. 추가 도움이 필요하시면 말씀해주세요.',
      type: 'text',
      status: 'read',
      isPinned: false,
      isEdited: false,
      readBy: ['student1', 'support1'],
      createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    },
    unreadCount: 0,
    isPinned: false,
    isMuted: true,
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
];

// ============ Mock 메시지 데이터 ============

export const mockMessages: Record<string, ChatMessage[]> = {
  room1: [
    {
      id: 'msg1-1',
      roomId: 'room1',
      senderId: 'system',
      senderName: '시스템',
      senderRole: 'admin',
      content: '논술 첨삭 채팅방이 생성되었습니다.',
      type: 'system',
      status: 'read',
      isPinned: false,
      isEdited: false,
      readBy: ['student1', 'expert1'],
      createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
      systemData: {
        action: 'room_created',
      },
    },
    {
      id: 'msg1-2',
      roomId: 'room1',
      senderId: 'student1',
      senderName: '김학생',
      senderRole: 'student',
      content: '안녕하세요, 선생님! 서울대 경영학과 논술 첨삭 부탁드립니다.',
      type: 'text',
      status: 'read',
      isPinned: false,
      isEdited: false,
      readBy: ['student1', 'expert1'],
      createdAt: new Date(Date.now() - 86400000 * 3 + 60000).toISOString(),
    },
    {
      id: 'msg1-3',
      roomId: 'room1',
      senderId: 'expert1',
      senderName: '김논술',
      senderRole: 'expert',
      content: '안녕하세요! 네, 논술 잘 확인했습니다. 전체적으로 구조는 좋으나 몇 가지 개선점이 있어요.',
      type: 'text',
      status: 'read',
      isPinned: false,
      isEdited: false,
      readBy: ['student1', 'expert1'],
      createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    },
    {
      id: 'msg1-4',
      roomId: 'room1',
      senderId: 'expert1',
      senderName: '김논술',
      senderRole: 'expert',
      senderImage: 'https://i.pravatar.cc/150?img=11',
      content: '첫 번째 문단에서 제시문 (가)의 핵심 논지를 더 명확히 제시해주세요.',
      type: 'text',
      status: 'read',
      isPinned: true,
      isEdited: false,
      readBy: ['student1', 'expert1'],
      createdAt: new Date(Date.now() - 86400000 * 2 + 60000).toISOString(),
    },
    {
      id: 'msg1-5',
      roomId: 'room1',
      senderId: 'student1',
      senderName: '김학생',
      senderRole: 'student',
      content: '아, 제시문 (가)의 주장을 더 구체적으로 인용해야 할까요?',
      type: 'text',
      status: 'read',
      isPinned: false,
      isEdited: false,
      readBy: ['student1', 'expert1'],
      createdAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      id: 'msg1-6',
      roomId: 'room1',
      senderId: 'expert1',
      senderName: '김논술',
      senderRole: 'expert',
      content: '네, 맞습니다. 직접 인용보다는 핵심 개념을 자신의 언어로 재구성하는 게 좋아요.',
      type: 'text',
      status: 'read',
      isPinned: false,
      isEdited: false,
      readBy: ['student1', 'expert1'],
      createdAt: new Date(Date.now() - 86400000 + 1800000).toISOString(),
      reactions: [
        {
          emoji: '👍',
          users: [{ userId: 'student1', name: '김학생' }],
          count: 1,
        },
      ],
    },
    {
      id: 'msg1-7',
      roomId: 'room1',
      senderId: 'student1',
      senderName: '김학생',
      senderRole: 'student',
      content: '수정본 올립니다. 확인 부탁드려요!',
      type: 'text',
      status: 'read',
      isPinned: false,
      isEdited: false,
      readBy: ['student1', 'expert1'],
      createdAt: new Date(Date.now() - 7200000).toISOString(),
    },
    {
      id: 'msg1-8',
      roomId: 'room1',
      senderId: 'student1',
      senderName: '김학생',
      senderRole: 'student',
      content: '',
      type: 'file',
      status: 'read',
      attachments: [
        {
          id: 'att1',
          type: 'file',
          url: '#',
          name: '서울대_논술_수정본.pdf',
          size: 245760,
          mimeType: 'application/pdf',
        },
      ],
      isPinned: false,
      isEdited: false,
      readBy: ['student1', 'expert1'],
      createdAt: new Date(Date.now() - 7200000 + 1000).toISOString(),
    },
    {
      id: 'msg1-9',
      roomId: 'room1',
      senderId: 'expert1',
      senderName: '김논술',
      senderRole: 'expert',
      content: '수정본 확인했습니다. 많이 좋아졌어요! 👏',
      type: 'text',
      status: 'delivered',
      isPinned: false,
      isEdited: false,
      readBy: ['expert1'],
      createdAt: new Date(Date.now() - 600000).toISOString(),
    },
    {
      id: 'msg1-10',
      roomId: 'room1',
      senderId: 'expert1',
      senderName: '김논술',
      senderRole: 'expert',
      content: '논리 전개 부분을 수정해보시면 좋을 것 같습니다.',
      type: 'text',
      status: 'delivered',
      isPinned: false,
      isEdited: false,
      readBy: ['expert1'],
      createdAt: new Date(Date.now() - 300000).toISOString(),
    },
  ],
  room2: [
    {
      id: 'msg2-1',
      roomId: 'room2',
      senderId: 'system',
      senderName: '시스템',
      senderRole: 'admin',
      content: '입시 컨설팅 채팅방이 생성되었습니다.',
      type: 'system',
      status: 'read',
      isPinned: false,
      isEdited: false,
      readBy: ['student1', 'consultant1'],
      createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
      systemData: {
        action: 'room_created',
      },
    },
    {
      id: 'msg2-2',
      roomId: 'room2',
      senderId: 'consultant1',
      senderName: '최입시',
      senderRole: 'consultant',
      content: '안녕하세요! 입시 전략 상담 시작하겠습니다. 목표 대학과 학과를 말씀해주세요.',
      type: 'text',
      status: 'read',
      isPinned: false,
      isEdited: false,
      readBy: ['student1', 'consultant1'],
      createdAt: new Date(Date.now() - 86400000 * 7 + 3600000).toISOString(),
    },
    {
      id: 'msg2-3',
      roomId: 'room2',
      senderId: 'student1',
      senderName: '김학생',
      senderRole: 'student',
      content: '서울대 경영학과, 연세대 경제학과를 목표로 하고 있습니다.',
      type: 'text',
      status: 'read',
      isPinned: false,
      isEdited: false,
      readBy: ['student1', 'consultant1'],
      createdAt: new Date(Date.now() - 86400000 * 6).toISOString(),
    },
    {
      id: 'msg2-4',
      roomId: 'room2',
      senderId: 'consultant1',
      senderName: '최입시',
      senderRole: 'consultant',
      content: '좋은 목표입니다! 두 학교 모두 논술 비중이 높으니 전략적으로 준비해야 해요.',
      type: 'text',
      status: 'read',
      isPinned: true,
      isEdited: false,
      readBy: ['student1', 'consultant1'],
      createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    },
    {
      id: 'msg2-5',
      roomId: 'room2',
      senderId: 'consultant1',
      senderName: '최입시',
      senderRole: 'consultant',
      content: '다음 상담 일정을 잡아볼까요?',
      type: 'text',
      status: 'read',
      isPinned: false,
      isEdited: false,
      readBy: ['student1', 'consultant1'],
      createdAt: new Date(Date.now() - 3600000).toISOString(),
    },
  ],
  room3: [
    {
      id: 'msg3-1',
      roomId: 'room3',
      senderId: 'system',
      senderName: '시스템',
      senderRole: 'admin',
      content: '논술 첨삭 채팅방이 생성되었습니다.',
      type: 'system',
      status: 'read',
      isPinned: false,
      isEdited: false,
      readBy: ['student1', 'expert2'],
      createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
      systemData: {
        action: 'room_created',
      },
    },
    {
      id: 'msg3-2',
      roomId: 'room3',
      senderId: 'expert2',
      senderName: '박전문',
      senderRole: 'expert',
      content: '연세대 논술 첨삭 완료했습니다. 결과를 확인해주세요!',
      type: 'text',
      status: 'read',
      isPinned: false,
      isEdited: false,
      readBy: ['student1', 'expert2'],
      createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    },
    {
      id: 'msg3-3',
      roomId: 'room3',
      senderId: 'student1',
      senderName: '김학생',
      senderRole: 'student',
      content: '첨삭 결과 확인했습니다. 감사합니다!',
      type: 'text',
      status: 'delivered',
      isPinned: false,
      isEdited: false,
      readBy: ['student1'],
      createdAt: new Date(Date.now() - 86400000).toISOString(),
    },
  ],
  room4: [
    {
      id: 'msg4-1',
      roomId: 'room4',
      senderId: 'student1',
      senderName: '김학생',
      senderRole: 'student',
      content: '결제 관련 문의드립니다. 프리미엄 플랜으로 업그레이드하려면 어떻게 해야 하나요?',
      type: 'text',
      status: 'read',
      isPinned: false,
      isEdited: false,
      readBy: ['student1', 'support1'],
      createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    },
    {
      id: 'msg4-2',
      roomId: 'room4',
      senderId: 'support1',
      senderName: '고객센터',
      senderRole: 'admin',
      content: '문의하신 내용 확인했습니다. 추가 도움이 필요하시면 말씀해주세요.',
      type: 'text',
      status: 'read',
      isPinned: false,
      isEdited: false,
      readBy: ['student1', 'support1'],
      createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    },
  ],
};

// ============ Mock 서비스 헬퍼 함수 ============

/**
 * 지연 시뮬레이션
 */
export const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

/**
 * 랜덤 ID 생성
 */
export const generateId = () => `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;

/**
 * 자동 응답 메시지 생성 (시뮬레이션용)
 */
export const generateAutoResponse = (roomId: string, _userMessage?: string): ChatMessage | null => {
  // _userMessage can be used for context-aware responses in the future
  void _userMessage;
  const room = mockChatRooms.find(r => r.id === roomId);
  if (!room) return null;

  const otherParticipant = room.participants.find(p => p.userId !== 'student1');
  if (!otherParticipant || otherParticipant.status === 'offline') return null;

  // 간단한 자동 응답 로직
  const responses = [
    '네, 확인했습니다.',
    '좋은 질문이네요!',
    '조금 더 구체적으로 설명해주실 수 있을까요?',
    '알겠습니다. 확인 후 답변드리겠습니다.',
    '좋은 방향으로 가고 있어요!',
  ];

  return {
    id: generateId(),
    roomId,
    senderId: otherParticipant.userId,
    senderName: otherParticipant.name,
    senderRole: otherParticipant.role,
    senderImage: otherParticipant.profileImage,
    content: responses[Math.floor(Math.random() * responses.length)],
    type: 'text',
    status: 'delivered',
    isPinned: false,
    isEdited: false,
    readBy: [otherParticipant.userId],
    createdAt: new Date().toISOString(),
  };
};

export default {
  mockParticipants,
  mockChatRooms,
  mockMessages,
  delay,
  generateId,
  generateAutoResponse,
};
